camunda.bpm.admin-user:
  id: demo
  password: demo

camunda.bpm.database.type: postgres

# Database
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres