-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.interests
(
    id integer NOT NULL,
    user_id integer,
    depa_country character(3) NOT NULL,
    depa_city character varying(64),
    dest_country character(3) NOT NULL,
    dest_city character varying(64),
    period_start date NOT NULL,
    period_end date NOT NULL,
    price double precision NOT NULL,
    num_seat bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.offers
(
    id integer NOT NULL,
    fly_id integer NOT NULL,
    depar_city character varying(64) NOT NULL,
    dest_city character varying(64) NOT NULL,
    date timestamp without time zone NOT NULL,
    price double precision NOT NULL,
    num_seat bigint NOT NULL,
    availability boolean NOT NULL,
    company character varying(64) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.offersadhoc
(
    id integer NOT NULL,
    interest_id integer,
    offer_id integer,
    token_uri character(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    surname character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(50) NOT NULL,
    birthday date NOT NULL,
    nationality character(3) NOT NULL,
    token character(20),
    cardnumber character(16),
    phonenumber character varying(10) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.interests
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.offersadhoc
    ADD FOREIGN KEY (interest_id)
    REFERENCES public.interests (id)
    NOT VALID;


ALTER TABLE public.offersadhoc
    ADD FOREIGN KEY (offer_id)
    REFERENCES public.offers (id)
    NOT VALID;

END;
